### ISSUE TITLE
Error classes and their NamedIndividuals

### ISSUE THREAD

**Issue by jonathanbona** [addiehl/neuropsychological-testing-ontology#4] opened 2019-04-05 19:53 UTC
NPT.owl has a number of **Error** classes at the top level that have (OBI) NamedIndividuals as instances:

<img width="1422" alt="Screen Shot 2019-04-05 at 2 50 10 PM" src="https://user-images.githubusercontent.com/78007/55652771-2484f800-57b2-11e9-8c3e-941d61e50421.png">

It looks like they've been there a while:
https://github.com/addiehl/neuropsychological-testing-ontology/blob/master/ontology/NPT.owl#L9738

**Comment by jonathanbona** [comment] 2019-04-05 20:08
Removing these classes and leaving the individuals didn't seem to break anything: https://github.com/jonathanbona/neuropsychological-testing-ontology/commit/382070ea2a8d70e052eeed7ecdd185ec27871a43

**Comment by mark-jensen** [comment] 2019-04-05 20:20
I've seen this behavior before and never been able to figure out the root cause. It may be due to use of the NI in a value or cardinality assertion in a subclass axiom, but I think there is more to it, perhaps an artifact of using an old version of the OWL API or Protege. Deleting them is ok, usually works, but I've also seen them mysteriously return.

**Comment by APCox** [comment] 2020-07-02 19:23
This error should be resolved (along with many others) in version 1.7.3.

**Comment by APCox** [comment] 2020-07-23 23:34
Errors were resolved in version 1.7.3

**Closed as completed by APCox** 2020-07-23 23:34 UTC
